# Generated by Django 4.2.9 on 2024-02-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("picture", models.ImageField(upload_to="Media")),
                ("city", models.CharField(max_length=40)),
                ("trip_type", models.CharField(max_length=10)),
                ("departure", models.DateTimeField()),
                ("return_date", models.DateField()),
                ("price", models.FloatField()),
            ],
        ),
    ]
